### ISSUE TITLE
Select SD Card for Android 5.0 and up

### ISSUE THREAD

**Issue by deckyfx** [btimofeev/UniPatcher#10]
Should support select external SD Card for android 5.0 and up

**Comment by btimofeev** [comment]
Do you have a few cards in your phone? My phone does not have a SD at all, so I can not understand something, please describe your problem in more detail.

**Comment by deckyfx** [comment]
Just 1 sdcard, the internal is in
/storage/emulated/0/

And the external is
/storage/C094-F4E3/

I use marsmallow,  maybe its has something to do with the permission? , some app, like Es explorer require to open Document app and select the external storage to open the write permission

**Comment by btimofeev** [comment]
In the settings you can specify a directory with roms. For the output directory it is better to specify the internal memory (it is possible that there will not be a write permission to external memory)

**Comment by btimofeev** [comment]
It will be possible to select files on SD card when we use the Storage Access Framework instead of direct paths to files. Now I started working on it https://github.com/btimofeev/UniPatcher/issues/16

**Comment by btimofeev** [comment]
The migration to Storage Access Framework is complete.  File selection on the SD card and in cloud hosting should now work.
