### ISSUE TITLE
Material 2 theme

### ISSUE THREAD

**Issue by sergioad** [btimofeev/UniPatcher#15]
Hi, could you create an all white and an all grey material design 2 theme? Times are changing and if an app does not covers the current design guidelines it feels alien to the OS

**Comment by btimofeev** [comment]
Yes, you are right, the old theme is already outdated. We need to think about how it will look.

**Comment by sergioad** [comment]
Basicaly all white with brown accents

**Comment by btimofeev** [comment]
What about the dark theme?

In General, it's time to change not only the theme: use the standard file selection dialog, show in the main window information about whether the patch is suitable for ROM, show patching progress in the main window.

**Comment by btimofeev** [comment]
I tried to remake themes. Write if anyone has any suggestions for improvement.

![themes](https://user-images.githubusercontent.com/1546407/62006436-3287cb80-b149-11e9-951d-2fed5f344e95.png)

**Comment by sergioad** [comment]
None, I love it
