### ISSUE TITLE
How to use file manager for searching patches file 

### ISSUE THREAD

**Issue by Darthfecker** [btimofeev/UniPatcher#21]
Update : Just realized I can just install the previous version

**Comment by btimofeev** [comment]
You can select the "Downloads" folder from the menu on the left.

Or you can select the item "Show internal storage" in the menu with three dots, and then an item with all available phone memory will appear in the left menu.

**Comment by Darthfecker** [comment]
Showing internal storage still doesn't works, nothing happened

**Comment by btimofeev** [comment]
After enabling this option on my phone, an item with the name of the phone appears in the menu on the left. All memory is available to me for selection when I click on this item. The behavior is the same in the Android emulator on the computer.

Anyway this file selection interface provides the standard Android Files app and I can't change its behavior. Apparently on different phones it works a little differently.

**Comment by btimofeev** [comment]
I changed the method of opening files a bit.  Now the file managers installed on the device should be presented in the left menu, you can select files through one of them.
