### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by comradekingu** [btimofeev/UniPatcher#22]
I am getting the notifications about updated strings from Transifex, but I havent logged in after EU-GDPR and I still can't without accepting a bunch of terms.
Can you perhaps move the translations to Hosted Weblate? https://hosted.weblate.org/hosting/
I can help with that if you add https://hosted.weblate.org/user/kingu/ as an admin. :)

**Comment by btimofeev** [comment]
Ok, we can try. 
I created a project and added you as an admin. But I have not figured out how to add files for translation.

**Comment by btimofeev** [comment]
Weblate doesn't seem to support markdown and plain text files (or I didn't find how to add these line-by-line translations.). I store faq, about and info for Gogle Play in these formats:

https://github.com/btimofeev/UniPatcher/tree/master/app/src/main/res/raw
https://github.com/btimofeev/UniPatcher/blob/master/google-play/en/google-play.txt

**Comment by comradekingu** [comment]
Top stuff. I changed the VCS from "Git" to "GitHub" and added the Fastlane in this component https://hosted.weblate.org/projects/unipatcher/metadata/
Also turned on spreading of translations to other projects, and the language consistency plugin (so that if a language is created, it will be there for both components).

**Comment by btimofeev** [comment]
I configured a webhook and added a commit bot.

Transifex itself does not commit anything, I upload changes from it manually. The project also needs to be approved on Weblate.

**Comment by btimofeev** [comment]
The project has been approved on Weblate, so we can start using it. I changed all links in the application to the new server.

I also converted the markdown files to html and added them as components. But I did not understand how to configure the addition of a new language for this. The site says that I must specify some kind of template.

**Comment by comradekingu** [comment]
I see these have been added
https://hosted.weblate.org/projects/unipatcher/about/
https://hosted.weblate.org/projects/unipatcher/faq/
where are the files to be added, and what should the convention for the translation files be?

**Comment by btimofeev** [comment]
Weblate works very poorly with HTML. I added a new line in the middle of the file and all translations below it broke. Now I don't even know how to edit the FAQ. Transifex worked much better with this :(

**Comment by comradekingu** [comment]
Should convert it to markdown, the HTML support is very basic.

**Comment by btimofeev** [comment]
I already had these lines in markdown.  I wrote above that I could not find where to select the markdown format and convert md to html.  

I spent a few hours yesterday and added everything in the main xml, there should be no problem with it.

**Comment by btimofeev** [comment]
@comradekingu Can Weblate be configured to not swap lines in xml? Or is there no such option?

**Comment by comradekingu** [comment]
@btimofeev I am not sure, using fuzziness for new strings based on old ones is possible, and it seems I set that up already.
The current update changed authorship of all strings to you, hoping that just happened once?
Where is the HTML coming from?
What are you trying to do when XML lines are swapped? The strings are tracked by ID, or whatever Android calls them.

**Comment by btimofeev** [comment]
Shuffling lines is not a problem, it's just not so familiar to me.

I transferred all the lines from html to xml, so unfortunately I was assigned to the authors.  This will not happen in the future.
