### ISSUE TITLE
Files Won't Stay

### ISSUE THREAD

**Issue by HolyTrinit** [btimofeev/UniPatcher#65]
Whenever I input a rom or patch the opposite one disappears which doesn't allow me to patch the rom, I saw that you need to access the developer setting or something but idk how 😐 it'd be great if I could get some help.

**Comment by btimofeev** [comment]
It looks like you have "Do not keep activities" enabled in your developer options. If so, then it must be turned off.

How to open developer options: https://developer.android.com/studio/debug/dev-options#enable

**Comment by btimofeev** [comment]
https://github.com/btimofeev/UniPatcher/discussions/78
