### ISSUE TITLE
BillingClient in F-Droid build final apk

### ISSUE THREAD

**Issue by linsui** [btimofeev/UniPatcher#66]
It's pulled in by com.github.penn5:donations. Could you change it to another lib which doesn't depend on BillingClient? Thanks!

**Comment by btimofeev** [comment]
Hello. Can you tell us in more detail what is the problem with BillingClient?

**Comment by linsui** [comment]
Sorry, I should have make it clear. It's not FOSS so it's not allowed in F-Droid.

**Comment by btimofeev** [comment]
F-Droid build does not use the billing client in any way. 

The library provides a choice: 
- use billing to GooglePlay build
- use payment via bitcoin for the rest builds

Perhaps there is some mention of client billing in the apk, but it is not used in this case.

If you know of a better library, please let me know.

**Comment by linsui** [comment]
Though the billingclient is not used, it's always pulled in and packaged into the apk. I don't know if there is any FOSS alternative.

**Comment by linsui** [comment]
Just ping me here. :)

**Comment by btimofeev** [comment]
@linsui I have released a new version, tag "v0.17.3"

**Comment by linsui** [comment]
Thanks!
